#! /bin/bash
set -u

## Returns a grep regexp to look for
## forbidden spellings.
function getForbiddenPat() {
  pat=$1
  if [[ "${pat:0:1}" == "!" ]]; then
    aux=${pat:1}
    echo "${aux//\|/[ -]\?}"
  elif [[ "$pat" =~ .*\|.* ]]; then
    echo "${pat//\|/[ -]}"
  elif [[ "$pat" =~ .*\ .* ]]; then
    echo "${pat// /[-]\?}"
  elif [[ "$pat" =~ .*-.* ]]; then
    echo "${pat//-/[ ]\\?}"
  fi
}

enforce=("data|type"    # enforce spelling of 'datatype', forbids 'data-type' and 'data type'
         "fix|point"
         "!fixed|point" # forbids all combinations of fixedpoint
         "pattern functor"
         "sub|tree"
         "type level"
         "type safe")

ok=true
IFS=,
for enf in ${enforce[*]}; do
  pat=$(getForbiddenPat "$enf")
  echo "{Enforcing: $pat}"
  grep -n --colour "$pat" src/*.lhs
  if [[ "$?" == "0" ]]; then
    ok=false
  fi
done

if $ok; then
  echo "You're ok! :)"
  exit 0
else
  echo "Be congruent!"
  exit 1
fi
